### ISSUE TITLE
text selection

### ISSUE THREAD

**Issue by arolson101** [hulufei/react-sortable-mixin#1]
This works great, but the text gets selected while dragging.  Can you cancel or disable selection?

**Comment by hulufei** [comment]
You can add a css class like this:

``` css
.noselect {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

Then add this class to the `body` in `onMoveBefore` to prevent text selection, and remove this class in `onMoveEnd` to restore browser's default behaviour.
